apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-working-nginx-deployment
  labels:
    app: not-working-nginx
spec:
  selector:
    matchLabels:
      app: not-working-nginx
  template:
    metadata:
      labels:
        app: not-working-nginx
    spec:
      containers:
      - name: not-working-nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: not-working-nginx-service
spec:
  selector:
    app: not-working-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: not-working-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: not-working-nginx-service
            port:
              number: 80
