apiVersion: apps/v1
kind: Deployment
metadata:
  name: working-nginx-deployment
  labels:
    app: working-nginx
spec:
  selector:
    matchLabels:
      app: working-nginx
  template:
    metadata:
      labels:
        app: working-nginx
    spec:
      containers:
      - name: working-nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: working-nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.121.40
  selector:
    app: working-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
